elaborations:
  - name: flood
    projectId: protezione-civile
    taskId: kfp+pipeline://protezione-civile/d1a561c8929e4a0ba851c937d80c86ed
    workflowId: kfp://protezione-civile/protezione_civile:9d571837bfab4797ac5c6d2bc5e5d411
    tag: water
    fixedParameters:

  - name: forest
    projectId: protezione-civile
    taskId: kfp+pipeline://protezione-civile/d1a561c8929e4a0ba851c937d80c86ed
    workflowId: kfp://protezione-civile/protezione_civile:9d571837bfab4797ac5c6d2bc5e5d411
    tag: forest
    fixedParameters:
      shapeArtifactName: bosco
      dataArtifactName: data_s2_deforestation

  - name: land
    projectId: protezione-civile
    taskId: kfp+pipeline://protezione-civile/d1a561c8929e4a0ba851c937d80c86ed
    workflowId: kfp://protezione-civile/protezione_civile:9d571837bfab4797ac5c6d2bc5e5d411
    fixedParameters:
      input1: bosco
      input2: data_s2_deforestation
