elaborations:
  - name: flood
    projectId: parcheggi-scheduler-2025
    taskId: kfp+pipeline://parcheggi-scheduler-2025/e933172794e446298fc3e16a5fd25a7d
    workflowId: kfp://parcheggi-scheduler-2025/pipeline_latest_parkings:e983d1792ffb484f9f44a2eb06d54826
    tag: water
    fixedParameters:
      input1: AOI_Garda
      input2: AOI_Rec.shp
      input3: Lakes_TN
      input4: idrspacq.shp
      input5: Rivers_TN
      input6: cif_pta2022_v.shp


  - name: forest
    projectId: parcheggi-scheduler-2025
    taskId: kfp+pipeline://parcheggi-scheduler-2025/e933172794e446298fc3e16a5fd25a7d
    workflowId: kfp://parcheggi-scheduler-2025/pipeline_latest_parkings:e983d1792ffb484f9f44a2eb06d54826
    tag: forest
    fixedParameters:
      input1: bosco
      input2: data_s2_deforestation

  - name: land
    projectId: parcheggi-scheduler-2025
    taskId: kfp+pipeline://parcheggi-scheduler-2025/e933172794e446298fc3e16a5fd25a7d
    workflowId: kfp://parcheggi-scheduler-2025/pipeline_latest_parkings:e983d1792ffb484f9f44a2eb06d54826
    fixedParameters:
      input1: bosco
      input2: data_s2_deforestation

  - name: test
    projectId: parcheggi-scheduler-2025   
    taskId: kfp+pipeline://parcheggi-scheduler-2025/e933172794e446298fc3e16a5fd25a7d
    workflowId: kfp://parcheggi-scheduler-2025/pipeline_latest_parkings:e983d1792ffb484f9f44a2eb06d54826
    tag: forest
    fixedParameters:
      input1: bosco
      input2: data_s2_deforestation